routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::resource('products', 'ProductController');

app/Product.php
<?php

namespace challenge;

use Illuminate\Database\Eloquent\Model;

use challenge\Tag;

class Product extends Model
{
    public $timestamps = false;
    protected $guarded = ['id'];
    protected $fillable = ['title', 'description', 'image', 'stock'];

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'products_tags', 'product_id', 'tag_id');
    }
}

app/Tag.php
<?php

namespace challenge;

use Illuminate\Database\Eloquent\Model;

use challenge\Product;

class Tag extends Model
{
    protected $fillable = ['name'];
    public $timestamps = false;

    public function products()
    {
        return $this->belongsToMany(Product::class, 'products_tags', 'tag_id', 'product_id');
    }
}

app/User.php
<?php

namespace challenge;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace challenge\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace challenge\Http\Controllers;

use Illuminate\Http\Request;

use challenge\Repositories\TagRepository;

class HomeController extends Controller
{
    protected $tags;
    
    public function __construct(TagRepository $tags)
    {
        $this->tags = $tags;
    }

    public function index()
    {
        return view('home', ['tags' => $this->tags->findMostUsed()]);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace challenge\Http\Controllers;

use Illuminate\Http\Request;

use challenge\Http\Requests\SaveProduct;
use challenge\Repositories\ProductRepository;
use challenge\Repositories\TagRepository;
use challenge\Product;
use challenge\Helpers\FileUploadHelper;

class ProductController extends Controller
{
    protected $products;
    protected $uploader;
    protected $tags;

    public function __construct(ProductRepository $products, FileUploadHelper $uploader, 
        TagRepository $tags)
    {
        $this->products = $products;
        $this->uploader = $uploader;
        $this->tags = $tags;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('products.index', ['products' => $this->products->findAll()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.form', 
            ['product' => new Product(), 'tags' => $this->tags->findAll(), 'tagsSelected' => null]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  SaveProduct  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SaveProduct $request)
    {
        $data = $request->all();
        $data['image'] = $this->uploader->save($request->image, 'images');

        $this->products->save($data);

        return redirect()
            ->route('products.index')
            ->with('success', 'Product created successfully!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = $this->products->findById($id);
        $tagsSelected = $product->tags->pluck('id');
        return view('products.form', 
            ['product' => $product, 'tags' => $this->tags->findAll(), 'tagsSelected' => $tagsSelected]);

        // return view('products.form', ['product' => $this->products->findById($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  SaveProduct  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SaveProduct $request, $id)
    {
        $data = $request->all();
        $data['image'] = $this->uploader->save($request->image, 'images');
        $this->products->update($data, $id);

        return redirect()
            ->route('products.index')
            ->with('success', 'Product successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = $this->products->findById($id);
        $imageIsDeleted = $this->uploader->delete($product->image, 'images');

        $this->products->remove($product);

        return response(['success' => 'Product has been deleted!', 'deleteImage' => $imageIsDeleted], 201);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Home')

@section('content')
    <div class="jumbotron">
        <h1 class="display-4">Product CRUD Challenge</h1>
        <hr class="my-4">
        <div class="row">
            <div class="col-md-6">
                <h4>Most Used Tags </h4>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Quantity</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($tags as $tag)
                            @if($tag->products_count > 0)
                                <tr>
                                    <td class="text-center">{{ $loop->iteration }}</td>
                                    <td class="text-center">{{ $tag->name }}</td>
                                    <td class="text-center">{{ $tag->products_count }}</td>
                                </tr>
                            @endif
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/alerts.blade.php
@if (session('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ session('success') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif
@if (session('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ session('error') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="pt-BR">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{{ asset('css/selectize.default.css') }}">
    <title>Challenge | @yield('title')</title>
  </head>
  <body>
    <div class="container">
      @include('layouts.menu')
      @yield('content')
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/selectize.min.js') }}"></script>
    <script src="{{ asset('js/scripts.js') }}"></script>
  </body>
</html>

resources/views/layouts/menu.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" title="Challenge" href="{{ url('/') }}">Challenge</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" title="Home" href="{{ url('/') }}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('products.index') }}">Products</a>
      </li>
    </ul>
  </div>
</nav>

resources/views/products/form.blade.php
@extends('layouts.app')

@section('title', 'Products List')

@section('content')
    <div class="card">
        <div class="card-header">
            Products
        </div>
        <div class="card-body">
            <h5 class="card-title">
                {{ empty($product->id) ? 'New Product' : 'Edit Product' }}
            </h5>
            @if($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if(empty($product->id))
                <form method="post" action="{{ route('products.store') }}" enctype="multipart/form-data" novalidate>
            @else
                <form method="post" action="{{ route('products.update', $product->id) }}" enctype="multipart/form-data" novalidate>
                @method('PUT')
            @endif
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" name="title" id="title" required class="form-control {{ $errors->first('title') ? 'is-invalid' : '' }}"
                            value="{{ old('title') ? old('title') : $product->title }}" autocomplete="off">
                        <div class="invalid-feedback">
                            {{$errors->first('title')}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" class="form-control {{ $errors->first('description') ? 'is-invalid' : '' }}"
                            id="description" rows="3">{{ old('description') ? old('description') : $product->description }}</textarea>
                        <div class="invalid-feedback">
                            {{$errors->first('description')}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="stock">Stock</label>
                        <input type="number" name="stock" id="stock" min="1" required 
                        class="form-control {{ $errors->first('stock') ? 'is-invalid' : '' }}"
                            value="{{ old('stock') ? old('stock') : $product->stock }}">
                        <div class="invalid-feedback">
                            {{$errors->first('stock')}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <input type="file" name="image" id="image" class="form-control {{ $errors->first('image') ? 'is-invalid' : '' }}">
                        <div class="invalid-feedback">
                            {{$errors->first('image')}}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tags">Tags</label>
                        {!! Form::select('tags[]', $tags, $tagsSelected, ['placeholder' => '--Select--', 
                          'id' => 'tags', 'multiple' => 'multiple']) !!}
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                </form>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('title', 'Products List')

@section('content')
    <div class="card">
        <div class="card-header">
            Products
        </div>
        <div class="card-body">
            <h5 class="card-title">Products List</h5>
            @include('layouts.alerts')
            <div class="row">
                <div class="col-md-3 offset-md-9 btn-add">
                    <a href="{{ route('products.create') }}" title="New Product" 
                        class="btn btn-primary btn-block">
                        New
                    </a>
                </div>
            </div>
            @if(count($products) > 0)
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th class="text-center">Image</th>
                            <th class="text-center">Stock</th>
                            <th class="text-center">
                                
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($products as $product)
                            <tr class="product">
                                <td class="align-middle">{{ $product->title }}</td>
                                <td class="text-center">
                                    <img class="product-img" src="{{ url('storage/images/'.$product->image) }}" title="{{ $product->title }}">
                                </td>
                                <td class="text-center align-middle">{{ $product->stock }}</td>
                                <td class="text-center align-middle">
                                    <a href="{{ route('products.edit', $product->id) }}">Edit</a>
                                    <a href="{{ route('products.destroy', $product->id) }}" class="btn-delete">
                                        Remove
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $products->links() }}
            @else
                <p>No records found.</p>
            @endif
        </div>
    </div>    
@endsection